spring.application.name=flavorcast
spring.datasource.url=jdbc:postgresql://localhost:5432/flavorcast
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

# Export this environment variable in your terminal before running
# Explicitly tell Spring AI to use the Google GenAI chat model
spring.ai.model.chat=google-genai

spring.ai.google.genai.api-key=${GEMINI_API_KEY}